# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-22 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myinsta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
